### ISSUE TITLE
Self host whatscloud

### ISSUE THREAD

**Issue by jimmykhlam** [whatscloud/whatscloud-android#2]
Hi, it seems like the whatscloud.io server has been shut down as whatsapp has launched their Web version. 

However, I am interested in hosting this service for my own personal use. I'd like to ask:
1. Is it possible to self host this service with the code here, and is it still compatible with latest whatsapp architecture?
2. Can you provide some instructions? 

I'd be interested in paying for a hosted version of this if you guys ever decide to provide such a service.

**Comment by whatscloud** [comment]
@jimmykhlam you'd need to develop your own backend API to self-host this.

Architecture hasn't changed, messages are still stored in an Android internal SQLite DB. Root access is still required to access it.

Please contact us at whatscloudapp@gmail.com to discuss this matter further.
